|SLD.data.version|1
||K|KEYWORDS|keyword1,keyword2,keyword3
sldopt.asm|1||0|-1|-1|Z|pages.size:8192,pages.count:224,slots.count:8,slots.adr:0,8192,16384,24576,32768,40960,49152,57344
sldopt.asm|3||0|4|32768|K|; some eol comments with keyword1 included
sldopt.asm|3||0|4|32768|T|
sldopt.asm|4||0|4|32769|T|
sldopt.asm|5||0|4|32770|K|; full line comment with keyword2 included (line without code)
sldopt.asm|7||0|4|32770|K|; some keyword3 here
sldopt.asm|7||0|4|32770|F|label1
sldopt.asm|7||0|4|32770|L|,label1,
sldopt.asm|8||0|4|32773|F|label2
sldopt.asm|8||0|4|32773|L|,label2,
sldopt.asm|13||0|4|32776|K|; some keyword1 also after SLDOPT specified (should not matter)
sldopt.asm|13||0|4|32776|T|
sldopt.asm|14||0|4|32777|T|
sldopt.asm|17||0|100|50000|K|; keyword2 in displacement block (displaced address reported)
sldopt.asm|17||0|100|50000|T|
sldopt.asm|26||22|1|60000|K|; WPMEM keyword1
sldopt.asm|26||23|1|60001|K|; keyword3
sldopt.asm|26||23|1|60001|T|
sldopt.asm|27||0|1|60002|F|someData
sldopt.asm|27||0|1|60002|L|,someData,
sldopt.asm|28||22|1|60004|K|; WPMEM keyword1
sldopt.asm|28||23|1|60005|K|; keyword3
sldopt.asm|28||23|1|60005|T|
sldopt.asm|22||37|1|60006|K|; WPMEM keyword1
sldopt.asm|23||37|1|60007|K|; keyword3
sldopt.asm|23||37|1|60007|T|
sldopt.asm|39||22|1|60008|K|; WPMEM keyword1
sldopt.asm|39||23|1|60009|K|; keyword3
sldopt.asm|39||23|1|60009|T|
