task:
  name: FreeBSD - map image environment and build process
  env:
    CIRRUS_CLONE_DEPTH: 1
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 1
    memory: 2G
  sw_versions_script: make --version; pkg --version; bash --version; diff --version; cc --version; c++ --version
  sw_install_script: pkg install -y gmake bash
  build_script: gmake clean && gmake -j3
  install_script: gmake install && gmake clean
  ## now try the built+installed sjasmplus with some tests and examples
  # this is not separate task, because that would need again build
  # of sjasmplus in new container instance, so just do everything in one task
  assemble_examples_script: ContinuousIntegration/test_folder_examples.sh
  assemble_tests_script: ContinuousIntegration/test_folder_tests.sh
