makefile_build_task:
  env:
    CIRRUS_CLONE_DEPTH: 1
  container:
    matrix:
      image: gcc:5
      image: gcc:6
      image: gcc:7
      image: gcc:8
    cpu: 3
    memory: 1G
  build_script: make clean && make -j3
  install_script: make install && make clean
  ## now try the built+installed sjasmplus with some tests and examples
  # this is not separate task, because that would need again build
  # of sjasmplus in new container instance, so just do everything in one task
  assemble_tests_script: ContinuousIntegration/test_folder_tests.sh
  assemble_examples_script: ContinuousIntegration/test_folder_examples.sh

pipe:
  name: coveralls.io coverage report
  #depends_on: makefile_build  ## saves some resources in case regular build fails, but that's rare
  env:
    CIRRUS_CLONE_DEPTH: 1
    # coveralls plugin variables (access token + job ID)
    COVERALLS_REPO_TOKEN: ENCRYPTED[d8f3d878d91ea465e92170a7d46f471aec4a507813b6c31faa630dd1a1380420827ebc017baa2157bf17b3ed95437aae]
    # makefile variables affecting build options
    DEBUG: 1
    COVERALLS_SERVICE: 1
  resources:
    cpu: 3
    memory: 1G
  steps:
    - image: gcc:7
      generate_gcov_script: make clean && make -j3 coverage
    - image: python:3.7
      install_coveralls_plugin_script: pip install cpp-coveralls
      # "-n" as the *.gcov files are already generated in the project root from previous step
      upload_gcov_data_script: cpp-coveralls -n -e lua5.1/ -e tolua++/ --dump coversall.json; cat coversall.json
