makefile_build_task:
  container:
    matrix:
      image: gcc:5
      image: gcc:6
      image: gcc:7
      image: gcc:8
    cpu: 1
    memory: 500M
  build_script: make clean && make
  install_script: make install
  ## now try the built+installed sjasmplus with some tests and examples
  # this is not separate task, because that would need again build
  # of sjasmplus in new container instance, so just do everything in one task
  assemble_tests_background_script: ContinuousIntegration/test_folder_tests.sh
  assemble_examples_background_script: ContinuousIntegration/test_folder_examples.sh
