task:
  name: FreeBSD - map image environment and build process
  env:
    CIRRUS_CLONE_DEPTH: 1
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 4
    memory: 4G
  submodules_script:
    - git submodule init
    - git submodule update
  sw_install_script: pkg lock pkg && pkg install -y gmake bash
  sw_versions2_script:
    - pkg --version || echo "no pkg"
    - bash --version || echo "no bash"
    - gmake --version || echo "no gmake"
    - diff --help || echo "no diff"
    - cc --version || echo "no cc"
    - c++ --version || echo "no c++"
  # regular binary build (will be not run, just testing the build process)
  build_script: gmake clean && gmake -j4 CC=cc CXX=c++
  # build only the unit test binary, and run unit-tests + tests through make
  test_script: gmake clean && gmake -j4 CC=cc CXX=c++ tests
