path_classifiers:
  test:
    - "cpp-src-tests/"
    - "ContinuousIntegration/"
    - "tests/"
    - "examples/"
  library:
    - "lua5.1/"
    - "tolua++/"
    - "unittest-cpp/"
  docs:
    - "docs/"

#queries:
  #- exclude: cpp/use-of-goto

extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - g++-8
    after_prepare:    # Customizable step used by all languages.
      - export GNU_MAKE=make
      - export GIT=true
    index:    # Customizable step used by all languages.
      build_command:
        - $GNU_MAKE -j2 -s
