path_classifiers:
  test:
    - "cpp-src-tests/"
    - "ContinuousIntegration/"
    - "tests/"
    - "examples/"
  library:
    - "lua5.1/"
    - "tolua++/"
    - "unittest-cpp/"
  docs:
    - "docs/"

queries:
  #- exclude: cpp/use-of-goto

extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - g++-8
    after_prepare:    # Customizable step used by all languages.
      - export GNU_MAKE=make
      - export GIT=true
    configure:    # Customizable step used only by C/C++ extraction.
      command:
        #- ./prepare_deps
    before_index:    # Customizable step used by all languages.
        # nothing to do for sjasmplus? (needs at least comment to be not "null"
    index:    # Customizable step used by all languages.
      build_command:
        - $GNU_MAKE -j2 -s
